force-app/main/default/objects/Game__c/Game__c.object-meta.xml
<CustomObject>
    <label>Game</label>
    <nameField>
        <displayFormat>GAME-{000000}</displayFormat>
        <label>Game Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Game__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Tie</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Move__c/Move__c.object-meta.xml
<CustomObject>
    <label>Move</label>
    <nameField>
        <label>Move Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Moves</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Player__c/Player__c.object-meta.xml
<CustomObject>
    <label>Player</label>
    <nameField>
        <displayFormat>PLAYER-{000000}</displayFormat>
        <label>Player Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Player__c/fields/Game__c.field-meta.xml
<CustomField>
    <fullName>Game__c</fullName>
    <label>Game</label>
    <referenceTo>Game__c</referenceTo>
    <relationshipLabel>Players</relationshipLabel>
    <relationshipName>Players</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Player__c/fields/Move__c.field-meta.xml
<CustomField>
    <fullName>Move__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Move</label>
    <referenceTo>Move__c</referenceTo>
    <relationshipLabel>Players</relationshipLabel>
    <relationshipName>Players</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Player__c/fields/PlayerMove__c.field-meta.xml
<CustomField>
    <fullName>PlayerMove__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Player Move</label>
    <referenceTo>PlayerMove__c</referenceTo>
    <relationshipLabel>Players</relationshipLabel>
    <relationshipName>Players</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Player__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Played</fullName>
            </value>
            <value>
                <fullName>Winner</fullName>
            </value>
            <value>
                <fullName>Loser</fullName>
            </value>
            <value>
                <fullName>Tie</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PlayerMove__c/PlayerMove__c.object-meta.xml
<CustomObject>
    <label>Player Move</label>
    <nameField>
        <displayFormat>PM-{000000}</displayFormat>
        <label>Player Move Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Player Moves</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PlayerMove__c/fields/Game__c.field-meta.xml
<CustomField>
    <fullName>Game__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Game</label>
    <referenceTo>Game__c</referenceTo>
    <relationshipLabel>Player Moves</relationshipLabel>
    <relationshipName>PlayerMoves</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PlayerMove__c/fields/Move__c.field-meta.xml
<CustomField>
    <fullName>Move__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Move</label>
    <referenceTo>Move__c</referenceTo>
    <relationshipLabel>Move Players</relationshipLabel>
    <relationshipName>MovePlayers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PlayerMove__c/fields/Player__c.field-meta.xml
<CustomField>
    <fullName>Player__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Player</label>
    <referenceTo>Player__c</referenceTo>
    <relationshipLabel>Player Moves</relationshipLabel>
    <relationshipName>PlayerMoves</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/lwcRpsArena.cls
public with sharing class lwcRpsArena {
    
    public class NewGameRequest {
        @AuraEnabled public Id userId;
        @AuraEnabled public Id opponentUserId;
        @AuraEnabled public Id moveId;
        @AuraEnabled public Boolean isRematch;
        @AuraEnabled public Id previousMatchId;
    }

    public static GameData newGame(NewGameRequest newGameRequest) {
        return null;
    }

    @AuraEnabled
    public static List<GameData> queryGamesByUser(Id userId) {
       
        List<Player__c> players = [select 
            Game__c
            from 
            Player__c 
            where User__c = :userId
        ];

        Set<Id> gameIds = new Set<Id>();
        for(Player__c p : players) gameIds.add(p.Game__c);

        List<Game__c> games = [select 
            Id,
            CreatedDate,
            LastModifiedDate,
            Status__c,
            (select Id, Status__c, Move__r.Name, User__c, User__r.Name from Players__r)
            from Game__c
            where Id = :gameIds
            order by Status__c, CreatedDate
        ];

        List<GameData> gameData = new List<GameData>();

        Set<Id> playersWithoutMoves = new Set<Id>();

        for(Game__c g : games) {
            
            GameData gd = new gameData();
            gd.gameId = g.Id;
            gd.createdDate = g.CreatedDate;
            gd.modifiedDate = g.LastModifiedDate;
            gd.status = g.Status__c;

            for(Player__c p : g.Players__r) {
                PlayerData pd = new PlayerData();
                pd.playerId = p.Id;
                pd.userId = p.User__c;
                pd.name = p.User__r.Name;
                pd.status = p.Status__c;
                if(p.Move__r != null) pd.move = p.Move__r.Name;
                else playersWithoutMoves.add(p.Id);
                if(pd.userId == userId) gd.currentPlayer = pd;
                else gd.opponent = pd;
            }

            if(g.Status__c == 'Pending') {
                gd.outcome = 'PENDING';
                gd.outcomeLabel = 'VS';
            }
            else if(g.Status__c == 'Tie') {
                gd.outcome = 'TIE';
                gd.outcomeLabel = 'TIED';
            }
            else if(g.Status__c == 'Completed') {
                if(gd.currentPlayer.status == 'Winner') {
                    gd.outcome = 'WIN';
                    gd.outcomeLabel = 'DEFEATED';
                }
                else if(gd.currentPlayer.status == 'Loser') {
                    gd.outcome = 'LOSE';
                    gd.outcomeLabel = 'DEFEATED BY';
                }
            }

            gameData.add(gd);
        }

        if(!playersWithoutMoves.isEmpty()) {
            List<PlayerMove__c> playerMoves = [select Id, Move__c, Player__c, Move__r.Name from PlayerMove__c where Player__c = :playersWithoutMoves];
            for(gameData gd : gameData) {
                for(PlayerMove__c pm : playerMoves) {
                    if(pm.Player__c == gd.currentPlayer.playerId) {
                        gd.currentPlayer.move = pm.Move__r.Name;
                        break;
                    }
                    if(pm.Player__c == gd.opponent.playerId) {
                        gd.opponent.move = pm.Move__r.Name;
                        break;
                    }
                }
            }
        }

        return gameData;

    }

    public class GameData {
        @AuraEnabled public Id gameId { get; set; }
        @AuraEnabled public DateTime createdDate { get; set; }
        @AuraEnabled public DateTime modifiedDate { get; set; }
        @AuraEnabled public String status { get; set; }
        @AuraEnabled public String outcome { get; set; }
        @AuraEnabled public String outcomeLabel { get; set; }
        @AuraEnabled public PlayerData currentPlayer { get; set; }
        @AuraEnabled public PlayerData opponent { get; set; }
    }

    public class PlayerData {
        @AuraEnabled public Id playerId { get; set; }
        @AuraEnabled public Id userId { get; set; }
        @AuraEnabled public String status { get; set; }
        @AuraEnabled public String name { get; set; }
        @AuraEnabled public String move { get; set; }
    }
    
}